// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aytnmnaeheahvukrrraq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5dG5tbmFlaGVhaHZ1a3JycmFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjExNjYsImV4cCI6MjA2MDYzNzE2Nn0.ii-k66mONu3I6JA26mZVG_0AGZLCgf7pdMrdzNvrGwA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);